variables:
    GIT_STRATEGY: clone

stages:
    - test

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

ClangFormatCheck:
  stage: test
  image: bce7edfda510
  script:
  - ./.github/automation/clang-format.sh

job_1:
  stage: test
  image: bce7edfda510
  script:
    - make
    - cd test
    - export XBYAK_AARCH64_SANITIZE=1
    - ./test_all.sh -g
    - ./test_all.sh -f
