name: C/C++ CI

on:
  push:
    branches: [ fjmaster ]
  pull_request:
    branches: [ fjmaster ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test_all
      run: cd test && ./test_all.sh    
